title: Sadly, this aint HTML
author: Robinson Crusoe
email: Robinson_Crusoe@CrusoeCorp.com
description: > # this means to ignore newlines until "baseurl:"
I was hoping that I can use html tags, but interestingly enough, I can only use Github markdown.

# social links
twitter_username: Robinson_Crusoe
github_username:  Robinson_Crusoe

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
